const Ziggy = {
  url: 'http:\/\/localhost',
  port: null,
  defaults: {},
  routes: {
    'debugbar.openhandler': { uri: '_debugbar\/open', methods: ['GET', 'HEAD'] },
    'debugbar.clockwork': {
      uri: '_debugbar\/clockwork\/{id}',
      methods: ['GET', 'HEAD'],
      parameters: ['id'],
    },
    'debugbar.assets.css': { uri: '_debugbar\/assets\/stylesheets', methods: ['GET', 'HEAD'] },
    'debugbar.assets.js': { uri: '_debugbar\/assets\/javascript', methods: ['GET', 'HEAD'] },
    'debugbar.cache.delete': {
      uri: '_debugbar\/cache\/{key}\/{tags?}',
      methods: ['DELETE'],
      parameters: ['key', 'tags'],
    },
    'debugbar.queries.explain': { uri: '_debugbar\/queries\/explain', methods: ['POST'] },
    'sanctum.csrf-cookie': { uri: 'sanctum\/csrf-cookie', methods: ['GET', 'HEAD'] },
    dashboard: { uri: 'dashboard', methods: ['GET', 'HEAD'] },
    'profile.edit': { uri: 'profile', methods: ['GET', 'HEAD'] },
    'profile.update': { uri: 'profile', methods: ['PATCH'] },
    'profile.destroy': { uri: 'profile', methods: ['DELETE'] },
    register: { uri: 'register', methods: ['GET', 'HEAD'] },
    login: { uri: 'login', methods: ['GET', 'HEAD'] },
    'password.request': { uri: 'forgot-password', methods: ['GET', 'HEAD'] },
    'password.email': { uri: 'forgot-password', methods: ['POST'] },
    'password.reset': {
      uri: 'reset-password\/{token}',
      methods: ['GET', 'HEAD'],
      parameters: ['token'],
    },
    'password.store': { uri: 'reset-password', methods: ['POST'] },
    'verification.notice': { uri: 'verify-email', methods: ['GET', 'HEAD'] },
    'verification.verify': {
      uri: 'verify-email\/{id}\/{hash}',
      methods: ['GET', 'HEAD'],
      parameters: ['id', 'hash'],
    },
    'verification.send': { uri: 'email\/verification-notification', methods: ['POST'] },
    'password.confirm': { uri: 'confirm-password', methods: ['GET', 'HEAD'] },
    'password.update': { uri: 'password', methods: ['PUT'] },
    logout: { uri: 'logout', methods: ['POST'] },
    'calendar.events': { uri: 'calendar\/events', methods: ['GET', 'HEAD'] },
    'bookmark.create': { uri: 'bookmark\/create', methods: ['GET', 'HEAD'] },
    'bookmark.store': { uri: 'bookmark', methods: ['POST'] },
    'bookmark.destroy': {
      uri: 'bookmark\/{bookmark}',
      methods: ['DELETE'],
      parameters: ['bookmark'],
      bindings: { bookmark: 'id' },
    },
    'analysis.index': { uri: 'analysis', methods: ['GET', 'HEAD'] },
    'analysis.bulkUpdate': {
      uri: 'analyses\/bulk-update\/{user}',
      methods: ['PATCH'],
      parameters: ['user'],
    },
    'analysis.edit': {
      uri: 'analyses\/{analysis}\/edit',
      methods: ['GET', 'HEAD'],
      parameters: ['analysis'],
      bindings: { analysis: 'id' },
    },
    'analysis.update': {
      uri: 'analyses\/{analysis}',
      methods: ['PATCH'],
      parameters: ['analysis'],
      bindings: { analysis: 'id' },
    },
    'interview.expected.analysis': {
      uri: 'interview\/{analysis}\/expected',
      methods: ['GET', 'HEAD'],
      parameters: ['analysis'],
      bindings: { analysis: 'id' },
    },
    'interview.analysis': { uri: 'interview\/analysis\/start', methods: ['POST'] },
    company: { uri: 'company', methods: ['GET', 'HEAD'] },
    'company.create': { uri: 'company\/create', methods: ['GET', 'HEAD'] },
    'company.store': { uri: 'company', methods: ['POST'] },
    'company.show': {
      uri: 'company\/{company}',
      methods: ['GET', 'HEAD'],
      parameters: ['company'],
      bindings: { company: 'id' },
    },
    'company.edit': {
      uri: 'company\/{company}\/edit',
      methods: ['GET', 'HEAD'],
      parameters: ['company'],
      bindings: { company: 'id' },
    },
    'company.update': {
      uri: 'company\/{company}',
      methods: ['PUT'],
      parameters: ['company'],
      bindings: { company: 'id' },
    },
    'company.destroy': {
      uri: 'company\/{company}',
      methods: ['DELETE'],
      parameters: ['company'],
      bindings: { company: 'id' },
    },
    'company.search': { uri: 'companies\/search', methods: ['GET', 'HEAD'] },
    entrysheet: { uri: 'entrysheet', methods: ['GET', 'HEAD'] },
    'entrysheet.create': { uri: 'entrysheet\/create', methods: ['GET', 'HEAD'] },
    'entrysheet.create.with.company': {
      uri: 'entrysheets\/create\/{company_id}',
      methods: ['GET', 'HEAD'],
      wheres: { company_id: '[0-9]+' },
      parameters: ['company_id'],
    },
    'entrysheet.store': { uri: 'entrysheet', methods: ['POST'] },
    'entrysheet.show': {
      uri: 'entrysheet\/{entrysheet}',
      methods: ['GET', 'HEAD'],
      parameters: ['entrysheet'],
      bindings: { entrysheet: 'id' },
    },
    'entrysheet.edit': {
      uri: 'entrysheet\/{entrysheet}\/edit',
      methods: ['GET', 'HEAD'],
      parameters: ['entrysheet'],
      bindings: { entrysheet: 'id' },
    },
    'entrysheet.update': {
      uri: 'entrysheet\/{entrysheet}',
      methods: ['PUT'],
      parameters: ['entrysheet'],
      bindings: { entrysheet: 'id' },
    },
    'entrysheet.destroy': {
      uri: 'entrysheet\/{entrysheet}',
      methods: ['DELETE'],
      parameters: ['entrysheet'],
      bindings: { entrysheet: 'id' },
    },
    'entrysheet.pdf': {
      uri: 'entrysheet\/{id}\/pdf',
      methods: ['GET', 'HEAD'],
      parameters: ['id'],
    },
    'entrysheet.search': { uri: 'entrysheets\/search', methods: ['GET', 'HEAD'] },
    'content.store': {
      uri: 'entrysheet\/{entrysheet}\/content',
      methods: ['POST'],
      parameters: ['entrysheet'],
      bindings: { entrysheet: 'id' },
    },
    'content.edit': {
      uri: 'entrysheet\/{entrysheet}\/content\/{content}\/edit',
      methods: ['GET', 'HEAD'],
      parameters: ['entrysheet', 'content'],
      bindings: { entrysheet: 'id', content: 'id' },
    },
    'content.update': {
      uri: 'entrysheet\/{entrysheet}\/content\/{content}',
      methods: ['PUT'],
      parameters: ['entrysheet', 'content'],
      bindings: { entrysheet: 'id', content: 'id' },
    },
    'content.destroy': {
      uri: 'entrysheet\/{entrysheet}\/content\/{content}',
      methods: ['DELETE'],
      parameters: ['entrysheet', 'content'],
      bindings: { entrysheet: 'id', content: 'id' },
    },
    'content.bulkUpdate': {
      uri: 'entrysheet\/{entrysheet}\/bulk-update',
      methods: ['PATCH'],
      parameters: ['entrysheet'],
      bindings: { entrysheet: 'id' },
    },
    'company.files.store': {
      uri: 'company\/{company}\/files',
      methods: ['POST'],
      parameters: ['company'],
      bindings: { company: 'id' },
    },
    'company.files.destroy': {
      uri: 'company\/files\/{file}',
      methods: ['DELETE'],
      parameters: ['file'],
      bindings: { file: 'id' },
    },
    'company.files.download': {
      uri: 'company\/files\/download\/{file}',
      methods: ['GET', 'HEAD'],
      parameters: ['file'],
      bindings: { file: 'id' },
    },
    'company.files.view': {
      uri: 'company\/files\/view\/{file}',
      methods: ['GET', 'HEAD'],
      parameters: ['file'],
    },
    'interview.execute': { uri: 'interview', methods: ['POST'] },
    'interview.expected': {
      uri: 'interview\/{entrysheet}\/{content}\/expected',
      methods: ['GET', 'HEAD'],
      parameters: ['entrysheet', 'content'],
      bindings: { entrysheet: 'id', content: 'id' },
    },
    'interview.start': { uri: 'interview\/start', methods: ['POST'] },
    'storage.local': {
      uri: 'storage\/{path}',
      methods: ['GET', 'HEAD'],
      wheres: { path: '.*' },
      parameters: ['path'],
    },
  },
};
if (typeof window !== 'undefined' && typeof window.Ziggy !== 'undefined') {
  Object.assign(Ziggy.routes, window.Ziggy.routes);
}
export { Ziggy };
